dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
  # Default target on travis-ci.
  # Used as conditional check in the install stage
  - HOST=x86_64-unknown-linux-gnu
  - CRATE_NAME=anyshortcut-cli

cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target

addons:
  apt:
    packages:
    - gcc-multilib
    # needed for musl targets
    - musl-tools

matrix:
  include:
  # Linux
  - os: linux
    env:
    - TARGET=i686-unknown-linux-musl
    - DOCKER_IMAGE_TAG=i686-musl
    script: bash ci/test-in-docker.sh

  - os: linux
    env:
    - TARGET=x86_64-unknown-linux-musl
    - DOCKER_IMAGE_TAG=x86_64-musl
    script: bash ci/test-in-docker.sh

  # OSX
  - os: osx
    env: TARGET=x86_64-apple-darwin
    script:
    - cargo test --target $TARGET --verbose

before_install:
- set -e
- rustup self update

install:
# prevent target re-add error from rustup
- if [[ $TRAVIS_OS_NAME = linux && $HOST != $TARGET ]]; then rustup target add $TARGET; fi

after_script: set +e

before_deploy:
- cargo build --target "$TARGET" --release --verbose

deploy:
  api_key:
    secure: "jS0oZYqAlGzrisNWiJW24JdxuALiNo9VuPRYcAiT5qQ6HH8wne/sFC5zWLq5HZmPVtnBUTXPGV3dfj0jYWADFIKW4Rhgu1nPShVhOEa3wmwptPaxiOZWgoV1yXvONYJmYRiI/Dko0tBGPJ/PDv6MuFPLFPlJXbeS8KDth5Am/8kSbGsoePpIGwhK7gadb2GCkfHTNX3rvzzUt8nYp3G7wNj6YCJL3YIu91OaYAAoWjOZZ/bwwreJKXEkeKfReUYPJfUJXzJXbsPZ0nFv2zljTMynE956JZOS1lBN59BIh8AeNvy4prng0YQSQdM/G9oOBBUQ7HfQhJRcWCUoTjjnP8iao9t2rCibsQ8xORaz5lQfW2n/VKV1DH/grveUG2fwjNirfm6VIRpCtfE1gdWCEMcG8xyUKNXdwiZRqJtoRulBFesrarJWXJjX0xsjDEimYNRinSYdrmPyXYIbqNVsNzUUD8ne7HCEZoYCyTWtl9q587mFr7PlLGUU62/syWiIqw3cttpY7jSbRIwEX7fedqXLQCTpF1q9e/KRD/zCAvRsUQ7Z4SgS0Xlnf/2GFElFhNy/LyCvqGbVoE3Nl0KJavkAUixyhuU3OkqDVzUSsMHRK9eOuW46r58AgA1erDoaaNV9rklnS+dtgNjO59ENq7e0El3+exuDvjqPm9PcXYY="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    # deploy only on stable channel that has TARGET env variable sets
    condition: $TRAVIS_RUST_VERSION = stable && $TARGET != ""
    tags: true
  provider: releases
  skip_cleanup: true

before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

branches:
  only:
  # release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

notifications:
  email:
    on_success: never
