[package]
name = "curl-http"
version = "0.1.0"
authors = ["Folyd <lyshuhow@gmail.com>"]

[dependencies]
failure = "0.1.2"
failure_derive = "0.1.2"
curl = "0.4.14"
serde = "1.0.71"
serde_json = "1.0.26"